#!/usr/bin/php
<?php

error_reporting(E_ALL);
function exceptions_error_handler($severity, $message, $filename, $lineno) {
  if (error_reporting() == 0) {
    return;
  }
  if (error_reporting() & $severity) {
    throw new ErrorException($message, 0, $severity, $filename, $lineno);
  }
}
set_error_handler('exceptions_error_handler');
require_once 'fable.inc.php';

$options = getopt("qh");
if (isset($options['h'])) {
  echo "puke feature runner.\n";
  echo "  USAGE puke [OPTIONS]\n";
  echo "    h Show this help text\n";
  echo "    q Quiet - Don't show Advise on next step\n";
  exit;
}
$runner = new FeatureRunner();
$reporter = new ConsoleReporter();
if (!isset($options['q'])) {
  $reporter->showAdvise();
}
$runner->run($reporter);

/*
TODO:

http://railscasts.com/episodes/155-beginning-with-cucumber

simpletest
http://www.simpletest.org/api/SimpleTest/WebTester/SimpleBrowser.html

*/
